### ISSUE TITLE
VirtualTB.render doesn't work

### ISSUE THREAD

**Issue by weristdas** [eyounx/VirtualTaobao#2]
hi, buddie. the variable 'c' in render (line 71 of the envs/virtualTB.py)  is not defined. i guess, should it be  'self.total_c' ?

**Comment by Roooooo** [comment]
>  i guess, should it be 'self.total_c' ?

You are right. Thanks for reporting the bug and it has been fixed in the commit https://github.com/eyounx/VirtualTaobao/commit/8c6d902ce3c69bb80e7dd07a4a8df7843d80ab58.
