### ISSUE TITLE
how to use it on personal dataset in my search Engine

### ISSUE THREAD

**Issue by jjw-AI** [eyounx/VirtualTaobao#3]
I am building an demo e-commerce search Engine  for recommending  item list to users  with DDPG reinforcement learning algorithm predicting  . But I am confused with the virtualTaobao as a virtual training environment to help me apply FL to the online system.
1  what The virtualTao help me for the above goal?
2  how to use the VirturalTao adapt my dataset for giving  score  to get topK list,can you give a example step for me ?
3 [virtualTB/SupervisedLearning/dataset.txt ] can you give a detail explanation for the features , label ,and  the number of clicks. AND why the lables is multi length？

**Comment by eyounx** [comment]
This Virtual-Taobao project provides an environment for testing recommendation algorithms. In other words, this is a (live) benchmark.

If you want to apply reinforcement learning to your own engine, you may want to follow the Virtual-Taobao paper to build a simulator for your engine, and then train your RL agent in that simulator.

**Comment by jjw-AI** [comment]
Thanks!........ It seems that I need build a simulator for my dataset. Can you give a detail info/explanation about how to define the state and action in the ReadMe?  There are so many dimensions , What  do they mean?`
![image](https://user-images.githubusercontent.com/11384622/71078261-f6bad480-21c3-11ea-9354-be880cbd37dc.png)
`
